version: '3.1'

services: 
    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: contacts
            POSTGRES_PASSWORD: contacts
            POSTGRES_DB: schedule

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080